version: '3.1'

services:
  setup:
    image: cve-client
    build:
      context: ./
      dockerfile: Dockerfile.client
    command: python3 ./activate-plugin.py
    container_name: client-container-setup
    network_mode: host
